name: Docker Image CI Java Spring Boot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag trung2910/spring-boot-docker-kubernetes:latest
    - name: Push the Docker image
      run: docker push trung2910/spring-boot-docker-kubernetes:latest
